import {StyleSheet,Dimensions} from 'react-native';
import controller from '../../components/controller/controller';

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    logo:{
        alignSelf:'center',
        marginTop:controller.w80,
        width:'80%'
    },
    loginContainer:{
        width:'80%',
        alignSelf:'center',
        marginTop:controller.w100,
        backgroundColor:'#e9e9e9d9',
        borderRadius:10
    },
    emailContainer:{
        paddingTop:30,
        paddingLeft:30,
        paddingBottom:15,
        paddingRight:20
    },
    headerText:{
        fontSize:14,
        fontFamily:'Ubuntu-Regular',
        color:'#7a7a7a'
    },
    Input:{
        paddingTop:10,
        fontSize:20,
        fontFamily:'Ubuntu-Regular',
        color:'black',
        borderBottomColor:'#7a7a7a',
        borderBottomWidth:1
    },
    passwordContainer:{
        paddingTop:6,
        paddingLeft:30,
        paddingBottom:40,
        paddingRight:20
    },
    rememberContainer:{
        paddingLeft:30,
        paddingBottom:30,
        justifyContent:'center',
    },
    rememberUnder:{
        flexDirection:'row',
    },
    rememberText:{
        paddingLeft:10,
        // paddingTop:3,
        fontSize:16,
        textAlignVertical:'center',
        fontFamily:'Ubuntu-Regular',
        color:'#7a7a7a'
    },
    btnContainer:{
        marginTop:30,
    },
    signUp:{
        alignSelf:'center',
        marginTop:controller.w45,
        justifyContent:'center'
    },
    signUpbtn:{
        justifyContent:'center',
        alignItems:'center'
    },
    signUptext:{
        fontSize:14,
        color:'#ffff',
        opacity:0.9,
        fontFamily:'Ubuntu-Regular',
        textAlign:'center',
        paddingRight:5
    },
    signupBtnText:{
        fontSize:18,
        // marginBottom:10,
        fontFamily:'Ubuntu-Regular',
        color:'#279Bff'
    },
    forgotText:{
        marginTop:20,
        fontSize:14,
        textAlign:'center',
        fontFamily:'Ubuntu-Regular',
        color:'#279Bff'
    },
    forgotContainer:{
        alignSelf:'center',
        width:Dimensions.get('screen').width -20,
        backgroundColor:'#e9e9e9',
        height:'100%',
        marginTop:controller.h400,
        borderTopLeftRadius:35,
        borderTopRightRadius:35,
        opacity:0.90,
        backfaceVisibility:'visible',
    },
    underForgot:{
        marginTop:40,
    },
    forgotHeaderText:{
        textAlign:'center',
        fontSize:22,
        color:'#454545',
        fontFamily:'Ubuntu-Bold'
    },
    forgotSubHeaderText:{
        marginTop:10,
        fontSize:16,
        textAlign:'center',
        color:'#7a7a7a',
        fontFamily:'Ubuntu-Regular',
        marginLeft:controller.w45,
        marginRight:controller.w45
    },
    forgotInputContainer:{
        marginTop:controller.w50,
        marginLeft:controller.w45,
        marginRight:controller.w45
    },
    resetCodeBtn:{
        marginTop:controller.w45
    },
    forgotSignUp:{
        marginTop:25,
        alignSelf:'center'
    },
    forgotSignUptext:{
        fontSize:14,
        color:'#7a7a7a',
        opacity:0.9,
        fontFamily:'Ubuntu-Regular',
        textAlign:'center',
        paddingTop:5,
        paddingRight:5
    },
    closeBtnContainer:{
        marginTop:controller.w45,
        alignSelf:'center',
    },
    closeImg:{
        width:25,
        height:25
    },
});